name: domain
description: A new Flutter package project.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6
  core: 
    path: "../core"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  firebase_remote_config: ^2.0.2

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
