name: news_app
description: News search app
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  presentation:
    path: "modules/presentation"
  domain:
    path: "modules/domain"
  data:
    path: "modules/data"
  core:
    path: "modules/core"

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4
  responsive_framework: ^0.1.7
  dio: ^4.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.20
  flutter_bloc: 
  equatable: ^2.0.3
  flutter_keyboard_visibility: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3    
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  injectable_generator: 
  mockito: ^5.1.0
  bloc_test: ^9.0.3
  http_mock_adapter: ^0.3.2

flutter:    
  uses-material-design: true
