name: presentation
description: A new Flutter package project.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  domain:
    path: "../domain"
  email_validator: ^2.0.1
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
    - assets/svg/

    
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
